### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by mediix** [RothAndrew/M-Files-Vault-Application-Template-for-Visual-Studio#1]
Hi,

I was not able to install your project template into my VS2015. I followed the steps you gave, the M-Files project template just doesn't show up in my create new project window.

Can you help?

**Comment by RothAndrew** [comment]
I actually have mine in an M-Files folder under the Visual C# folder. Give that a try.

The full path for mine is "C:\Users\Andrew Roth\Documents\Visual Studio 2015\Templates\ProjectTemplates\Visual C#\M-Files\MFVaultApplicationTemplate.zip"

**Comment by mediix** [comment]
Thank you. I have made the changes to make it look like your path. Still no luck.

What Visual Studio version are you on? I have 2015 community.
